language: node_js
node_js:
  - '8'

cache:
  yarn: true

jobs:
  include:
    - stage: test
      script: npm run lint
    - stage: test
      script: npm run test-flow
    - stage: test
      script: npm run test-client && npm run test-saucelabs
    - stage: test
      script: npm run coverage && npm run benchmark
    - stage: deploy
      deploy:
        - provider: script
          skip_cleanup: true
          script: tools/docs
          on:
            tags: true
        - provider: script
          skip_cleanup: true
          script: tools/publish
          on:
            tags: true
