#!/bin/bash
#
# Publish the package to NPM
#

TAG=$(git tag -l --contains HEAD)
echo $TAG

if [[ -z $TAG ]]; then
	echo "No tag found."
else
	echo "Tag found ${TAG}."
fi

echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
# npm publish
