#!/bin/bash
#
# Publish the package to NPM
#

echo "git describe"
git describe

echo "git tag -l"
git tag -l --contains HEAD

echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

# npm publish
